name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH into VPS, pull latest code, and redeploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          if [ ! -d "Tools" ]; then
            git clone https://github.com/Jisan09/Tools.git Tools
          else
            cd Tools
            git pull
          fi
          cd Tools
          docker-compose up --build -d
